/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as MinhasViagensIndexRouteImport } from './routes/minhas-viagens/index'
import { Route as MinhasViagensTripIdRouteImport } from './routes/minhas-viagens/$tripId'
import { Route as RoteiroTokenRouteImport } from './routes/roteiro/$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasViagensIndexRoute = MinhasViagensIndexRouteImport.update({
  id: '/minhas-viagens/',
  path: '/minhas-viagens/',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhasViagensTripIdRoute = MinhasViagensTripIdRouteImport.update({
  id: '/minhas-viagens/$tripId',
  path: '/minhas-viagens/$tripId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoteiroTokenRoute = RoteiroTokenRouteImport.update({
  id: '/roteiro/$token',
  path: '/roteiro/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/perfil': typeof PerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/minhas-viagens/$tripId': typeof MinhasViagensTripIdRoute
  '/roteiro/$token': typeof RoteiroTokenRoute
  '/minhas-viagens/': typeof MinhasViagensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/perfil': typeof PerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/minhas-viagens/$tripId': typeof MinhasViagensTripIdRoute
  '/roteiro/$token': typeof RoteiroTokenRoute
  '/minhas-viagens': typeof MinhasViagensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chat': typeof ChatRoute
  '/perfil': typeof PerfilRoute
  '/api/chat': typeof ApiChatRoute
  '/minhas-viagens/$tripId': typeof MinhasViagensTripIdRoute
  '/roteiro/$token': typeof RoteiroTokenRoute
  '/minhas-viagens/': typeof MinhasViagensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chat'
    | '/perfil'
    | '/api/chat'
    | '/minhas-viagens/$tripId'
    | '/roteiro/$token'
    | '/minhas-viagens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chat'
    | '/perfil'
    | '/api/chat'
    | '/minhas-viagens/$tripId'
    | '/roteiro/$token'
    | '/minhas-viagens'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/chat'
    | '/perfil'
    | '/api/chat'
    | '/minhas-viagens/$tripId'
    | '/roteiro/$token'
    | '/minhas-viagens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ChatRoute: typeof ChatRoute
  PerfilRoute: typeof PerfilRoute
  ApiChatRoute: typeof ApiChatRoute
  MinhasViagensTripIdRoute: typeof MinhasViagensTripIdRoute
  RoteiroTokenRoute: typeof RoteiroTokenRoute
  MinhasViagensIndexRoute: typeof MinhasViagensIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-viagens/': {
      id: '/minhas-viagens/'
      path: '/minhas-viagens'
      fullPath: '/minhas-viagens/'
      preLoaderRoute: typeof MinhasViagensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minhas-viagens/$tripId': {
      id: '/minhas-viagens/$tripId'
      path: '/minhas-viagens/$tripId'
      fullPath: '/minhas-viagens/$tripId'
      preLoaderRoute: typeof MinhasViagensTripIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roteiro/$token': {
      id: '/roteiro/$token'
      path: '/roteiro/$token'
      fullPath: '/roteiro/$token'
      preLoaderRoute: typeof RoteiroTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ChatRoute: ChatRoute,
  PerfilRoute: PerfilRoute,
  ApiChatRoute: ApiChatRoute,
  MinhasViagensTripIdRoute: MinhasViagensTripIdRoute,
  RoteiroTokenRoute: RoteiroTokenRoute,
  MinhasViagensIndexRoute: MinhasViagensIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
